collection_name: agent
persist_directory: chroma_db
embedding_function: text-embedding-v4
k: 3
data_path: data
md5_hex_store: md5.txt
allow_knowledge_file_type: [".pdf", ".txt"]

chunk_size: 1000
chunk_overlap: 20
separators: ["\n\n", "\n", "!", ".", "?", "。", "！", "？", " ", ""]